services:
  - type: web
    name: samplemse2-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb://Achin:admin@ac-gkxo5tk-shard-00-00.nooj3hz.mongodb.net:27017,ac-gkxo5tk-shard-00-01.nooj3hz.mongodb.net:27017,ac-gkxo5tk-shard-00-02.nooj3hz.mongodb.net:27017/sample?ssl=true&replicaSet=atlas-12738f-shard-0&authSource=admin&appName=Cluster5
      - key: JWT_SECRET
        value: 4d4e5c084b8b0ae8ad90e2dd306250f9dc3f3e0cc7451b49a85eea929896b57d
      - key: NODE_ENV
        value: production

  - type: web
    name: samplemse2-frontend
    runtime: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: samplemse2-backend
          property: url
